### PR TITLE
[CCXDEV-8873] Fix bdd tests duplicates

### PR DESCRIPTION
**Pull request by juandspy**
# Description

These changes fixes some `AmbiguousStep` errors among others.

The tests are still broken for me as there is no docker-compose or something we can use to run them. I had to figure out how to setup the kafka broker, database tables, etc. and I think it's outside the scope of this task.

Fixes #[CCXDEV-8873](https://issues.redhat.com/browse/CCXDEV-8873)

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Testing steps

Manually ran the 

## Checklist
* [ ] Pylint passes for Python sources
* [ ] sources has been pre-processed by Black
* [ ] updated documentation wherever necessary

### CODE REVIEW

**Review by tisnik — COMMENTED** [review]
have just one comment - common_cli is in fact not common, but pretty concrete
LGTM instead

**Comment by juandspy** [comment]
> have just one comment - common_cli is in fact not common, but pretty concrete LGTM instead

updated

**Review by epapbak — APPROVED** [review]
If I didn't miss anything, lgtm

**Review by tisnik — APPROVED** [review]
ok

**Pull request merged**
