### PR TITLE
Update some fields according to the UI changes

### PR DESCRIPTION
**Pull request by juandspy**
Fix the errors found by @gkarat in https://github.com/RedHatInsights/insights-behavioral-spec/pull/69.

### CODE REVIEW

**Review by tisnik — COMMENTED** [review]
Are these bugs or changed made in UI sometime?

**Comment by juandspy** [comment]
> Are these bugs or changed made in UI sometime?

Maybe "bug" was not the right word :) Changed.

**Review by tisnik — APPROVED** [review]
LGTM

**Review by Bee-lee — APPROVED** [review]
trust ya:)

**Pull request merged**
