### PR TITLE
Enhance sorting scenario with the category column

### PR DESCRIPTION
**Pull request by gkarat**
# Description

This modifies `features/Insights_Advisor/recommendations_page_sorting.feature` and improves the sorting scenario by mentioning the "category" column. The sorting by category in the Advisor recommendation list is done by comparing the first category for each rule (a rule can have more than one category).

## Type of change

Please delete options that are not relevant.

- New test scenario added into existing feature file
- Non-breaking change in test steps implementation

### CODE REVIEW

**Comment by gkarat** [comment]
@tisnik, @juandspy, @Fewwy, please, take a look 👋🏼

**Comment by Fewwy** [comment]
@gkarat LGTM

**Review by Fewwy — APPROVED** [review]

**Review by tisnik — APPROVED** [review]
LGTM

**Review by tisnik — APPROVED** [review]
Seems legit

**Comment by gkarat** [comment]
@tisnik can we merge it? :)

**Pull request merged**
