### PR TITLE
Notification service tests update

### PR DESCRIPTION
**Pull request by epapbak**
# Description

- Improve the way notification DB is cleaned up and prepared between tests
- Refactor some steps

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- Refactor (refactoring code, removing useless files)

## Testing steps

Ran all notification-related tests

## Checklist
* [x] Pylint passes for Python sources
* [x] sources has been pre-processed by Black
* [ ] updated documentation wherever necessary

### CODE REVIEW

**Review by tisnik — COMMENTED** [review]
given...
...
...
-> background

**Comment by epapbak** [comment]
> given...
> ...
> ...
> -> background

even in the tests that don't need it? I have no real issue with leaving it as background, TBH, but the steps are executed for each test

**Comment by epapbak** [comment]
> > given...
> > ...
> > ...
> > -> background
> 
> even in the tests that don't need it? I have no real issue with leaving it as background, TBH, but the steps are executed for each test

Fixed =)

**Comment by tisnik** [comment]
> > given...
> > ...
> > ...
> > -> background
> 
> even in the tests that don't need it? I have no real issue with leaving it as background, TBH, but the steps are executed for each test

not for all tests, just for these that need it, for sure

**Review by tisnik — APPROVED** [review]
ok

**Review by joselsegura — APPROVED** [review]

**Pull request merged**
