### PR TITLE
Fix check_prediction_result_ignoring_field step

### PR DESCRIPTION
**Pull request by juandspy**
# Description

This step wasn't well defined. Fixing a couple of bugs in it: name and deleting keys that may not exist.

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Testing steps

Locally.

## Checklist
* [x] Pylint passes for Python sources
* [x] sources has been pre-processed by Black
* [ ] updated documentation wherever necessary
* [ ] new tests can be executed both locally and within docker container

### CODE REVIEW

**Review by tisnik — COMMENTED** [review]
why it is needed?

**Comment by juandspy** [comment]
> why it is needed?

WDYM? @tisnik the function was introduced in https://github.com/RedHatInsights/insights-behavioral-spec/pull/393

**Comment by tisnik** [comment]
> > why it is needed?
> 
> WDYM? @tisnik the function was introduced in #393

yes I know, as I reviewed it. But does this change means that the fields are not present in some situation? Or why is `del` not appropriate there?

**Review by Bee-lee — APPROVED** [review]

**Review by tisnik — APPROVED** [review]
ok

**Pull request merged**
